modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="bloodsmeltery"
version="1.1.5a"
displayName="Blood Smeltery"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blood-smeltery"
updateJSONURL="https://raw.githubusercontent.com/SmileycorpMC/Blood-Smeltery/1.18/update.json"
credits=""
authors="Smileycorp"
description="Adds the ablity to create Life Essence and Rune blocks in the Tinker's Construct Smeltery."

[[dependencies.bloodsmeltery]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.5.1.31,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.bloodsmeltery]]
    modId="mantle"
    mandatory=true
    versionRange="[1.9.27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bloodsmeltery]]
    modId="bloodmagic"
    mandatory=true
    versionRange="[1.18.2-3.2.2-37,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.bloodsmeltery]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18.2-71.1,)"
    ordering="NONE"
    side="BOTH"