modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="bloodsmeltery"
version="1.1.3"
displayName="Blood Smeltery"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blood-smeltery"
updateJSONURL="https://github.com/SmileycorpMC/Blood-Smeltery/tree/1.16/update.json"
credits=""
authors="Smileycorp"
description="Adds the ablity to create Life Essence and Rune blocks in the Tinker's Construct Smeltery."

[[dependencies.bloodsmeltery]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.3.4.335,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.bloodsmeltery]]
    modId="mantle"
    mandatory=true
    versionRange="[1.6.157,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bloodsmeltery]]
    modId="bloodmagic"
    mandatory=true
    versionRange="[1.16.4-3.1.11-34,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.bloodsmeltery]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-53.3,)"
    ordering="NONE"
    side="BOTH"